name: CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions repository 5
        uses: actions/checkout@v2
      - name: deploy to server
        uses: jsfluxdev/test@main
        with:
          host: ${{ secrets.UBUNTU_SERVER_HOST }}
          username: ${{ secrets.UBUNTU_SERVER_USERNAME }}
          key: ${{ secrets.UBUNTU_SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu
