name: CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: debian-latest
    steps:
      - name: Checkout actions repository3
        uses: actions/checkout@v2
      - name: deploy to server
        uses: jsfluxdev/test@main
        with:
          host: ${{ secrets.DEBIAN_SERVER_HOST }}
          username: ${{ secrets.DEBIAN_SERVER_USERNAME }}
          key: ${{ secrets.DEBIAN_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/videoconf  # 필요에 따라 디렉토리 경로 조정
